# Generated by Django 4.2.20 on 2025-05-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='swap_type',
        ),
    ]
