# Generated by Django 4.2.20 on 2025-05-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_related_swap_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_request', 'New Request'), ('counter_offer', 'Counter Offer')], default=None, max_length=50, null=True),
        ),
    ]
