# Generated by Django 4.2.20 on 2025-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ratings',
            field=models.IntegerField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
