# Generated by Django 4.2.20 on 2025-05-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_swap',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
